on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: chmod +x gradlew

      - run: ./gradlew build
        env:
          GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: chmod +x gradlew

      - run: ./gradlew test
        env:
          GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "Deployment completed successfully!"
